name: wai-git-http
version: '0.0.0'
synopsis: Git http-backend CGI App of WAI
description: ! 'This WAI application library handles static files,

  executes CGI scripts, and serves as a reverse proxy

  (including EventSource).'
category: Web, Yesod
author: Tom Sydney Kerckhove <syd.kerckhove@gmail.com>
maintainer: Tom Sydney Kerckhove <syd.kerckhove@gmail.com>
license: BSD3
homepage: https://github.com/NorfairKing/wai-git-http
git: git@github.com:NorfairKing/wai-git-http.git
dependencies:
- bytestring
- conduit >=1.1
- conduit-extra
- directory
- process
- wai >=3.2 && <3.3
library:
  ghc-options: -Wall
  source-dirs: src
  exposed-modules:
  - Network.Wai.Application.CGI.Git
  - Network.Wai.Application.CGI.Git.Conduit
  dependencies:
  - base >=4 && <5
  - attoparsec >=0.10.0.0
  - blaze-builder
  - case-insensitive
  - containers
  - http-types >=0.7
  - network
  - sockaddr
  - text
  - wai-conduit
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -Wall
    dependencies:
    - base
    - hspec >=1.3
    - wai-git-http
    - warp
