name: wai-app-file-cgi
version: '3.1.3'
synopsis: File/CGI/Rev Proxy App of WAI
description: ! 'This WAI application library handles static files,

  executes CGI scripts, and serves as a reverse proxy

  (including EventSource).'
category: Web, Yesod
author: Kazu Yamamoto <kazu@iij.ad.jp>
maintainer: Kazu Yamamoto <kazu@iij.ad.jp>
license: BSD3
homepage: http://www.mew.org/~kazu/proj/mighttpd/
git: git://github.com/kazu-yamamoto/wai-app-file-cgi
extra-source-files:
- test/cgi-bin/broken
- test/cgi-bin/echo-env
- test/data/post
- test/html/index.html
- test/html/ja/index.html.ja
- test/html/no_extension
- test/html/redirect/index.html
dependencies:
- bytestring
- conduit >=1.1
- conduit-extra
- directory
- filepath
- unix
- wai >=3.2 && <3.3
- warp >=3.2.6 && <3.3
library:
  ghc-options: -Wall
  source-dirs: src
  exposed-modules:
  - Network.Wai.Application.CGI.Git
  dependencies:
  - base >=4 && <5
  - array
  - attoparsec >=0.10.0.0
  - attoparsec-conduit
  - blaze-builder
  - blaze-html
  - case-insensitive
  - containers
  - data-default-class
  - http-client >=0.5
  - http-conduit >=2.1
  - http-date
  - http-types >=0.7
  - io-choice
  - lifted-base
  - mime-types
  - network
  - process
  - sockaddr
  - static-hash
  - text
  - transformers
  - wai-conduit
  - word8
tests:
  doctest:
    main: doctests.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -Wall
    dependencies:
    - base
    - doctest >=0.9.3
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -Wall
    dependencies:
    - base
    - hspec >=1.3
    - http-types
    - wai-app-file-cgi
    - HTTP
